### ISSUE TITLE
Error .__compiled: file not found

### ISSUE THREAD

**Issue by theskyblockman** [Belluxx/Java2Smali#1]
Hello, I was trying to run the software and got this error:
```
java.lang.RuntimeException: .__compiled: file not found
        at com.android.dex.util.FileUtils.readFile(FileUtils.java:51)
        at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:168)
        at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:143)
        at com.android.dx.command.dexer.Main.processOne(Main.java:678)
        at com.android.dx.command.dexer.Main.processAllFiles(Main.java:575)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:310)
        at com.android.dx.command.dexer.Main.runDx(Main.java:288)
        at com.android.dx.command.dexer.Main.main(Main.java:244)
        at com.android.dx.command.Main.main(Main.java:95)
        at com.technodeveloper.java2smali.util.ToolsManager.runDx(ToolsManager.java:11)
        at com.technodeveloper.java2smali.util.ConversionManager.dexClassFolder(ConversionManager.java:98)
        at com.technodeveloper.java2smali.Main.convert(Main.java:96)
        at com.technodeveloper.java2smali.Main.convertAndClean(Main.java:71)
        at com.technodeveloper.java2smali.Main.convertAndClean(Main.java:61)
        at com.technodeveloper.java2smali.Main.init(Main.java:55)
        at com.technodeveloper.java2smali.Main.main(Main.java:22)
1 error; aborting
```
I think it's an easy fix but currently im not able to use any jdk so I can't fix the issue myself (I only have an outdated jre available)

**Comment by Techno-Developer** [comment]
I'm sorry but i tried to run it on my laptop and it works perfectly both for single files and directories.
Have you tried to run it on a computer with a recent and clean JDK/JRE?

**Comment by theskyblockman** [comment]
Yes I tried with java 8 and 16. The problem is that I can't reproduce the issue because I switched my OS and now I don't have any problem. Is the error linked to Windows?

**Comment by Belluxx** [comment]
@theskyblockman Maybe, however i cannot verify because i don't use Windows
